title: Our Activities
classNames: flex row wrap
columns:
  - title: Online Coding Lessons
    body: Learn coding from anywhere with us! Join our interactive online lessons led by passionate tech educators. Perfect for learning comfortably at home.

    button:
      link: 
      text: Read more

  - title: Join the Club
    body: Get hands-on with robotics! Join our in-person Robotics Club for learning, experimenting, and collaborating with peers. Build, program, and develop critical skills in a fun, supportive environment.
    button:
      link: 
      text: Read more

  - title: Strive for Glory
    body: Showcase your skills! Participate in robotics and coding competitions to demonstrate creativity, collaboration, and coding prowess. Push boundaries and excel in technology with us.
    button:
      link: 
      text: Read more
